{
 "title": "Service overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Ingress (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(my_space_grpc_my_app_requests_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses from the server (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(my_space_grpc_my_app_responses_total[10s])",
     "legendFormat": "{{status}}:{{method}}"
    }
   ]
  },
  {
   "title": "Response time quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\n    sum(rate(my_space_grpc_my_app_histogram_response_time_seconds_bucket[10s])) by (le, status)\n)",
     "legendFormat": "0.9q : {{status}}"
    },
    {
     "expr": "histogram_quantile(0.5,\n    sum(rate(my_space_grpc_my_app_histogram_response_time_seconds_bucket[10s])) by (le, status)\n)",
     "legendFormat": "0.5q : {{status}}"
    }
   ]
  }
 ]
}